version: '3'
services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    volumes:
      - mongo-data:/data/db
    ports:
        - "27017:27017"
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=mydb
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local