services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    volumes:
      - mongo-data:/data/db
    ports:
        - "27017:27017"
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=mydb
      - PORT=4000
    depends_on:
      - mongodb
    ports:
      - "4000:4000"
    volumes:
      - mongo-data:/data/db
      - ./app:/usr/src/app
      - /usr/src/app/node_modules

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'

  grafana:
    build: ./grafana
    ports:
      - "3000:3000"

volumes:
  mongo-data:
    driver: local